"""Initial migration.

Revision ID: 4b47f4c14bb4
Revises: 
Create Date: 2023-04-11 11:09:20.454875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b47f4c14bb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('vt_api_key', sa.String(length=120), nullable=False),
    sa.Column('ibm_api_key', sa.String(length=120), nullable=False),
    sa.Column('ipapi_api_key', sa.String(length=120), nullable=False),
    sa.Column('abuseipdb_api_key', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
